name: Daily Validation Request

on:
  schedule:
    # Runs daily at 12:30 AM UTC
    - cron: "30 0 * * *"

jobs:
  validate-user:
    runs-on: ubuntu-latest

    steps:
    - name: Run Docker Container
      run: |
        # Add Docker's official GPG key:
        sudo apt-get update
        sudo apt-get install ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        # Pull the Docker image
        sudo docker pull santhosh9515/grampanchayat
        
        # Run the Docker container
        sudo docker run -d --name validation-container santhosh9515/grampanchayat

    - name: Send POST Request to /validateuser
      run: |
        # Wait for the service to be ready
        sleep 30  # Adjust this if needed based on your service startup time
        
        # Send POST request with email and password
        curl -X POST http://localhost:8080/validateuser \
        -H "Content-Type: application/json" \
        -d '{"email": "ksanthosh20ka1a0554@gmail.com", "password": "sathish"}'
    - name: Stop and Remove Docker Container
      run: |
        docker stop validation-container
        docker rm validation-container
