name: Daily Validation Request

on:
  schedule:
    # Runs daily at 12:30 AM UTC
    - cron: "30 0 * * *"

jobs:
  validate-user:
    runs-on: ubuntu-latest

    steps:
    - name: Run Docker Container
      run: |
        sudo apt-get update
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
        # Pull the Docker image
        sudo docker pull santhosh9515/grampanchayat
        
        # Run the Docker container
        sudo docker run -d --name validation-container santhosh9515/grampanchayat

    - name: Send POST Request to /validateuser
      run: |
        # Wait for the service to be ready
        sleep 30  # Adjust this if needed based on your service startup time
        
        # Send POST request with email and password
        curl -X POST http://localhost:8080/validateuser \
        -H "Content-Type: application/json" \
        -d '{"email": "ksanthosh20ka1a0554@gmail.com", "password": "sathish"}'
    - name: Stop and Remove Docker Container
      run: |
        docker stop validation-container
        docker rm validation-container
